version: '3'

services:
#  hardware-coverity:
#    container_name: hardware-coverity
#    build:
#      context: hardware-coverity-go/
#    ports:
#    - '666:666'
#    networks:
#    - hc
  #ELK
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elasticsearch
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
    - cluster.name=helix-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
    - hc
  kibana:
    # container_name: dashboard_kibana
    image: docker.elastic.co/kibana/kibana:6.4.3
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
    - "5601:5601"
    networks:
    - hc
    depends_on:
    - elasticsearch
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:6.4.3
#    container_name: logstash
#    ports:
#    - "9600:9600"
#    - "5044:5044/tcp"
#    links:
#    - elasticsearch
#    volumes:
#    - ./logstash/config:/config-dir/
#    command: logstash -f /config-dir/logstash.conf
#    depends_on:
#    - elasticsearch

# docker network, use the docker default, bridge
networks:
  hc:
    driver: bridge

